version: '3.8'
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - controle-placa

  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: "CONTROLE_PLACA"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - 3306:3306
    networks:
      - controle-placa

networks:
  controle-placa:
    driver: bridge